I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 646, in script
    Brooks "Do you want my blanket? I'm not using it."
Exception: Sayer 'Brooks' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 646, in script
    Brooks "Do you want my blanket? I'm not using it."
  File "D:\renpy-7.3.5-sdk\renpy\ast.py", line 678, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\renpy-7.3.5-sdk\renpy\ast.py", line 576, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'Brooks' is not defined.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
W2 Dating Sim 1.0
Sat Mar 06 14:38:28 2021
