I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 155, in script
    show cody sad at lefft
  File "game/script.rpy", line 155, in <module>
    show cody sad at lefft
NameError: name 'lefft' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 155, in script
    show cody sad at lefft
  File "D:\renpy-7.3.5-sdk\renpy\ast.py", line 1183, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "D:\renpy-7.3.5-sdk\renpy\ast.py", line 1142, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "D:\renpy-7.3.5-sdk\renpy\python.py", line 2059, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\renpy-7.3.5-sdk\renpy\python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 155, in <module>
    show cody sad at lefft
NameError: name 'lefft' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
W2 Dating Sim 1.0
Thu Apr 29 22:23:28 2021
